{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aionbd.fullname" . }}-secret
  labels:
    {{- include "aionbd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
